parameters:
#    ez_systems_comments.example.class: EzSystems\CommentsBundle\Example

services:
#    ez_systems_comments.example:
#        class: %ez_systems_comments.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
