parameters:
    ez_comments.renderer.class: EzSystems\CommentsBundle\Comments\CommentsRenderer
    ez_comments.twig.extension.class: EzSystems\CommentsBundle\Twig\Extension\CommentsExtension
    ez_comments.provider.factory.class: EzSystems\CommentsBundle\Comments\Provider\SiteAccessAwareFactory
    ez_comments.provider.disqus.class: EzSystems\CommentsBundle\Comments\Provider\Disqus

services:
    ez_comments.renderer:
        class: %ez_comments.renderer.class%
        calls:
            - [setDefaultProviderLabel, [%ez_comments.default.default_provider%]]

    ez_comments.twig.extension:
        class: %ez_comments.twig.extension.class%
        arguments: [@ez_comments.renderer]
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: twig.extension }

    ez_comments.provider.factory:
        class: %ez_comments.provider.factory.class%
        arguments: [@ezpublish.config.resolver, @templating]

    ez_comments.provider.disqus:
        class: %ez_comments.provider.disqus.class%
        factory_service: ez_comments.provider.factory
        factory_method: buildDisqus
        arguments: [%ez_comments.provider.disqus.class%]
        tags:
            - { name: ez_comments.provider, alias: disqus }
