parameters:
    ez_comments.renderer.class: EzSystems\CommentsBundle\Comments\CommentsRenderer
    ez_comments.twig.extension.class: EzSystems\CommentsBundle\Twig\Extension\CommentsExtension
    ez_comments.provider.template_based.class: EzSystems\CommentsBundle\Comments\Provider\TemplateBasedProvider
    ez_comments.provider.disqus.class: EzSystems\CommentsBundle\Comments\Provider\Disqus
    ez_comments.default.disqus.default_template: "EzSystemsCommentsBundle::disqus.html.twig"

services:
    ez_comments.renderer:
        class: %ez_comments.renderer.class%

    ez_comments.twig.extension:
        class: %ez_comments.twig.extension.class%
        arguments: [@ez_comments.renderer]
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: twig.extension }

    ez_comments.provider.template_based:
        abstract: true
        class: %ez_comments.provider.template_based.class%
        arguments: [@templating]

    ez_comments.provider.disqus:
        class: %ez_comments.provider.disqus.class%
        parent: ez_comments.provider.template_based
        calls:
            - [setDefaultTemplate, [%ez_comments.default.disqus.default_template%]]
            - [setShortName, [%ez_comments.default.disqus.shortname%]]
        tags:
            - { name: ez_comments.provider, alias: disqus }
